version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: polymind
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - polymind-network

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GROQ_API_KEY: ${GROQ_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX_NAME: ${PINECONE_INDEX_NAME}
    depends_on:
      - db
    networks:
      - polymind-network

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    networks:
      - polymind-network

networks:
  polymind-network:
    driver: bridge

volumes:
  postgres_data:
